<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                name="OTS" 
                nsPrefix="ots" 
                nsURI="http://www.example.com/ots">

  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Tutor" eSuperTypes="ots:User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BankAccount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TutoringOffers" eType="ots:TutoringOffer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="WeeklyAvailability" eType="ots:AvailabilitySlot" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="ots:User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TutoringRequests" eType="ots:TutoringRequest" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TutoringOffer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExpertiseLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HourlyPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="AvailabilitySlot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DayOfWeek" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TutoringRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RequestedSubject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RequestedLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RequestedDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tutor" eType="ots:Tutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Student" eType="ots:Student"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TutoringSession">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SessionDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SessionDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SessionPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tutor" eType="ots:Tutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Student" eType="ots:Student"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PaymentDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountPaid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TutoringSession" eType="ots:TutoringSession"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="SessionCancellation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CancellationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TutoringSession" eType="ots:TutoringSession"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TutorOfTheMonthAward">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AwardMonth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tutor" eType="ots:Tutor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AwardedForSubject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

</ecore:EPackage>
