<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                name="TileO" 
                nsPrefix="tileo" 
                nsURI="http://www.example.com/tileo">

  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PlayerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CurrentTile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HasWon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Tile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TileID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsActionTile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsVisited" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConnectedTiles" eType="tileo:Tile" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ActionCard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ActionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ActionDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Players" eType="tileo:Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tiles" eType="tileo:Tile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActionCards" eType="tileo:ActionCard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CurrentPlayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HiddenTile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumTurnsActionTileActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="GameBoard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tiles" eType="tileo:Tile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BoardLayout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

</ecore:EPackage>
